pipeline {
    agent any

    

    stages {
        stage('Checkout') {
            steps {
                // Clone the Git repository
                git branch: 'main', url: 'https://github.com/kalyan2360/Project.git'
            }
        }

        stage('Build') {
            steps {
                // Run Maven build
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run Maven tests
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                // Package the application (if not covered in the build step)
                sh 'mvn package'
            }
        }

        stage('Deploy') {
            steps {
                // Add deployment logic if needed
                echo 'Deployment stage (customize as needed)'
            }
        }
    }

}
